'use strict';
const PIN = '2026';
const STORAGE = { guests:'lirandzo_emerald_guest_registry_v10', rsvps:'lirandzo_emerald_rsvps_v2', checkins:'lirandzo_emerald_checkins_v1' };
const EVENT_ID = 'LZD-ESM-2026';
const CODE_PATTERN = /^LZD-ESM-[A-Z0-9]{4,}$/i;
const $ = (selector, context = document) => context.querySelector(selector);
let stream=null, scanTimer=null, detector=null, lastRaw='', lastRawAt=0, pendingUnknown=null;
function getStore(key,fallback=[]){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
function setStore(key,value){localStorage.setItem(key,JSON.stringify(value))}
function escapeHTML(value){return String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function normalizeCode(code){return String(code||'').trim().toUpperCase()}
function formatDate(value){return new Intl.DateTimeFormat('pt-PT',{dateStyle:'short',timeStyle:'medium'}).format(new Date(value))}
function getGuests(){return getStore(STORAGE.guests,[])}
function findGuest(payload){const guests=getGuests();const code=normalizeCode(payload?.code);const token=String(payload?.token||'').toLowerCase();const name=String(payload?.name||payload?.guest||'').toLowerCase();return guests.find(g=>normalizeCode(g.code)===code||String(g.token||'').toLowerCase()===token||String(g.name||'').toLowerCase()===name)||null}
function parseScanValue(raw){const text=String(raw||'').trim();if(!text)return null;try{const data=JSON.parse(text);if(data&&(data.type==='lirandzo-checkin'||data.code)){return{raw:text,event:data.event||EVENT_ID,code:normalizeCode(data.code),name:data.guest||data.name||'Convidado',guests:data.guests||'1',table:data.table||'Mesa por definir',token:data.token||'',package:data.package||'Pacote Esmeralda'}}}catch{}const code=normalizeCode(text);if(CODE_PATTERN.test(code))return{raw:text,event:EVENT_ID,code,name:'Convidado',guests:'1',table:'Mesa por definir',package:'Pacote Esmeralda'};const guest=getGuests().find(g=>String(g.name||'').toLowerCase().includes(text.toLowerCase()));if(guest)return{raw:text,event:EVENT_ID,code:guest.code,name:guest.name,guests:guest.maxGuests,table:guest.table,token:guest.token,package:'Pacote Esmeralda'};return null}
function getRsvpByCode(code){return getStore(STORAGE.rsvps,[]).find(item=>normalizeCode(item.code)===normalizeCode(code))}
function getCheckinByCode(code){return getStore(STORAGE.checkins,[]).find(item=>normalizeCode(item.code)===normalizeCode(code))}
function saveCheckin(payload,source='camera'){const list=getStore(STORAGE.checkins,[]);const existing=list.find(item=>normalizeCode(item.code)===normalizeCode(payload.code));if(existing)return existing;const guest=findGuest(payload);const rsvp=getRsvpByCode(payload.code);const entry={code:normalizeCode(payload.code),name:guest?.name||rsvp?.name||payload.name||'Convidado',guests:String(guest?.maxGuests||rsvp?.guests||payload.guests||'1'),table:guest?.table||rsvp?.table||payload.table||'Mesa por definir',group:guest?.group||rsvp?.group||'Convidados',event:payload.event||EVENT_ID,package:payload.package||'Pacote Esmeralda',source,timestamp:new Date().toISOString()};list.unshift(entry);setStore(STORAGE.checkins,list);renderRecords();renderStats();return entry}
function setResult(type,title,text,payload=null){const card=$('#resultCard');card.classList.remove('ok','warn','error');if(type)card.classList.add(type);$('#resultTitle').textContent=title;$('#resultText').textContent=text;const guest=$('#guestResult'),copyBtn=$('#copyResult'),confirmBtn=$('#confirmUnknown');if(payload){$('#guestName').textContent=payload.name||'Convidado';$('#guestCode').textContent=normalizeCode(payload.code);$('#guestMeta').textContent=`${payload.guests||'1'} pessoa(s) · ${payload.table||'Mesa por definir'} · ${payload.package||'Pacote Esmeralda'}`;guest.hidden=false;copyBtn.hidden=false}else{guest.hidden=true;copyBtn.hidden=true}confirmBtn.hidden=!pendingUnknown}
function validatePayload(payload,source='camera'){if(!payload||!CODE_PATTERN.test(normalizeCode(payload.code))){pendingUnknown=null;setResult('error','QR Code inválido','Este QR Code não pertence a este convite ou não contém um código de entrada válido.');beep('error');return}const guest=findGuest(payload);const rsvp=getRsvpByCode(payload.code);const duplicate=getCheckinByCode(payload.code);const normalized={...payload,code:normalizeCode(payload.code),name:guest?.name||rsvp?.name||payload.name||'Convidado',guests:guest?.maxGuests||rsvp?.guests||payload.guests||'1',table:guest?.table||rsvp?.table||payload.table||'Mesa por definir',package:payload.package||'Pacote Esmeralda'};if(duplicate){pendingUnknown=null;setResult('warn','Entrada já validada',`Este convidado já fez check-in em ${formatDate(duplicate.timestamp)}.`,duplicate);beep('warn');return}if(!guest&&getGuests().length>0){pendingUnknown=normalized;setResult('warn','Convidado não encontrado','O código tem formato válido, mas não consta na lista de convidados deste dispositivo. Valide manualmente apenas se a equipa confirmar.',normalized);beep('warn');return}const entry=saveCheckin(normalized,source);pendingUnknown=null;vibrateSuccess();beep('ok');setResult('ok','Entrada permitida','Check-in confirmado com sucesso.',entry)}
async function startScanner(){const video=$('#cameraPreview'),frame=$('#scannerFrame');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=stream;await video.play();frame.classList.add('is-camera-on');$('#startScanner').disabled=true;$('#stopScanner').disabled=false;setResult('','Scanner activo','Aponte a câmara para o QR Code do convite.');if('BarcodeDetector'in window){try{detector=new BarcodeDetector({formats:['qr_code']})}catch{detector=null}}scanLoop()}catch{setResult('error','Não foi possível abrir a câmara','Verifique a permissão da câmara. Em ficheiros locais, alguns navegadores exigem HTTPS ou servidor local. Use o modo manual.')}}
function stopScanner(){if(scanTimer)cancelAnimationFrame(scanTimer);scanTimer=null;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;detector=null;$('#cameraPreview').srcObject=null;$('#scannerFrame').classList.remove('is-camera-on');$('#startScanner').disabled=false;$('#stopScanner').disabled=true}
async function scanLoop(){const video=$('#cameraPreview'),canvas=$('#scanCanvas'),context=canvas.getContext('2d',{willReadFrequently:true});const tick=async()=>{if(!stream||video.readyState<2){scanTimer=requestAnimationFrame(tick);return}let raw='';if(detector){try{const codes=await detector.detect(video);raw=codes?.[0]?.rawValue||''}catch{detector=null}}if(!raw&&window.jsQR){const size=480;canvas.width=size;canvas.height=size;const ratio=Math.min(video.videoWidth,video.videoHeight);const sx=(video.videoWidth-ratio)/2,sy=(video.videoHeight-ratio)/2;context.drawImage(video,sx,sy,ratio,ratio,0,0,size,size);const img=context.getImageData(0,0,size,size);const qr=window.jsQR(img.data,img.width,img.height,{inversionAttempts:'dontInvert'});raw=qr?.data||''}if(raw){const now=Date.now();if(raw!==lastRaw||now-lastRawAt>2400){lastRaw=raw;lastRawAt=now;validatePayload(parseScanValue(raw),'camera')}}scanTimer=requestAnimationFrame(tick)};tick()}
function vibrateSuccess(){if(navigator.vibrate)navigator.vibrate([55,35,55])}
function beep(type='ok'){try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=type==='ok'?760:type==='warn'?420:220;gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.08,ctx.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.18);osc.start();osc.stop(ctx.currentTime+.2)}catch{}}
function renderStats(){const guests=getGuests(),checkins=getStore(STORAGE.checkins,[]);$('#statGuests').textContent=guests.length;$('#statChecked').textContent=checkins.length;$('#statPending').textContent=Math.max(0,guests.length-checkins.length);$('#statTables').textContent=new Set(guests.map(g=>g.table).filter(Boolean)).size}
function renderRecords(){const list=getStore(STORAGE.checkins,[]);$('#checkedCount').textContent=list.length;$('#recordsList').innerHTML=list.length?list.map(item=>`<article class="record-item"><div><strong>${escapeHTML(item.name)}</strong><small>${escapeHTML(formatDate(item.timestamp))} · ${escapeHTML(item.table||'Mesa por definir')} · ${escapeHTML(item.guests)} pessoa(s)</small></div><span>${escapeHTML(item.code)}</span></article>`).join(''):'<p>Ainda não existem entradas validadas neste dispositivo.</p>';renderStats()}
function exportCsv(){const list=getStore(STORAGE.checkins,[]);const rows=[['Nome','Codigo','Mesa','Pessoas','Grupo','Evento','Pacote','Data']].concat(list.map(i=>[i.name,i.code,i.table,i.guests,i.group,i.event,i.package,i.timestamp]));const csv=rows.map(row=>row.map(v=>`"${String(v||'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='checkins-lirandzo-v10.csv';link.click();URL.revokeObjectURL(link.href)}
function initPanel(){if(!navigator.mediaDevices?.getUserMedia){$('#scanSupportNote').textContent='Este navegador não permite acesso directo à câmara. Use o modo manual.';$('#startScanner').disabled=true}else if(!('BarcodeDetector'in window)){$('#scanSupportNote').textContent='Este navegador tentará usar a biblioteca QR. Se estiver offline e não carregar, use o modo manual.'}$('#startScanner').addEventListener('click',startScanner);$('#stopScanner').addEventListener('click',stopScanner);$('#manualForm').addEventListener('submit',e=>{e.preventDefault();validatePayload(parseScanValue($('#manualCode').value),'manual');$('#manualCode').value=''});$('#confirmUnknown').addEventListener('click',()=>{if(!pendingUnknown)return;const entry=saveCheckin(pendingUnknown,'manual-confirmed');pendingUnknown=null;vibrateSuccess();beep('ok');setResult('ok','Entrada validada manualmente','A equipa confirmou o convidado e registou a entrada.',entry)});$('#copyResult').addEventListener('click',async()=>{const text=`${$('#guestName').textContent} · ${$('#guestCode').textContent} · ${$('#guestMeta').textContent}`;try{await navigator.clipboard.writeText(text)}catch{alert(text)}});$('#exportCheckins').addEventListener('click',exportCsv);$('#clearCheckins').addEventListener('click',()=>{if(!confirm('Limpar todos os registos de check-in deste dispositivo?'))return;setStore(STORAGE.checkins,[]);renderRecords();setResult('','Registos limpos','Os check-ins deste dispositivo foram limpos.')});renderRecords();renderStats()}
function init(){ $('#pinForm').addEventListener('submit',e=>{e.preventDefault();if($('#teamPin').value.trim()!=='2026'){alert('PIN incorrecto.');return}$('#pinCard').hidden=true;$('#checkerPanel').hidden=false;initPanel()}) }
document.addEventListener('DOMContentLoaded',init);window.addEventListener('pagehide',stopScanner);
