// Dados do casamento Minoca & Abubacar - gerado pela Lirandzo
window.LIRANDZO_EVENT = {
  "slug": "minoca-abubacar",
  "coupleNames": "Minoca & Abubacar",
  "displayNames": "Nura e Abubacar",
  "bride": "Minoca Isabel Muianga",
  "groom": "Abubacar Amisse Amade",
  "monogram": "MA",
  "eventType": "Casamento",
  "language": "Português",
  "visualStyle": "Elegante, romântico e minimalista, com sensibilidade estética apropriada para noivos muçulmanos",
  "colors": "Marfim, branco, dourado suave, verde sálvia e castanho quente",
  "dateISO": "2026-08-29T09:00:00+02:00",
  "eventDateLong": "29 de agosto de 2026",
  "rsvpDeadline": "",
  "timezone": "Africa/Maputo",
  "verse": "Com amor, gratidão e bênçãos, convidamo-lo(a) a celebrar este momento especial connosco.",
  "verseReference": "Celebração com amor e gratidão",
  "brideParents": "Família Muianga",
  "groomParents": "Família Amade",
  "ceremonyTitle": "Cerimónia Civil",
  "ceremonyPlace": "Thayana Eventos",
  "ceremonyTime": "13:00",
  "ceremonyMap": "https://www.google.com/maps/search/?api=1&query=Thendane%20Eventos",
  "receptionTitle": "Copo de Água",
  "receptionPlace": "Thayana Eventos",
  "receptionTime": "15:00",
  "receptionMap": "https://www.google.com/maps/search/?api=1&query=Thendane%20Eventos",
  "additionalTitle": "",
  "additionalPlace": "",
  "additionalTime": "",
  "photoTitle": "",
  "photoPlace": "",
  "photoTime": "",
  "welcomeDrinkTitle": "",
  "welcomeDrinkPlace": "",
  "welcomeDrinkTime": "",
  "supportContacts": "",
  "supportWhatsapp": "",
  "estimatedGuests": 0,
  "guestRows": 0,
  "giftSectionType": "Lista de presentes",
  "bankAccounts": [],
  "mobilePayments": [],
  "program": [
    {
      "title": "Cerimónia Civil",
      "place": "Thayana Eventos",
      "time": "13:00"
    },
    {
      "title": "Copo de Água",
      "place": "Thayana Eventos",
      "time": "15:00"
    }
  ],
  "story": {},
  "letter": "Querido(a) convidado(a),\n\nSerá uma honra partilhar consigo este momento único das nossas vidas. Esperamos por si para celebrarmos juntos com alegria, carinho e gratidão.\n\nCom carinho,\nMinoca e Abubacar",
  "audioYoutube": "",
  "audioMp3": "",
  "civilMap": "https://www.google.com/maps/search/?api=1&query=Thendane%20Eventos",
  "guestListVersion": "Lista de convidados",
  "guestListUpdatedAt": "2026-06-05"
};

window.LIRANDZO_GUESTS = [];
