// Dados do casamento Calate & Helder - gerado pela Lirandzo
window.LIRANDZO_EVENT = {
  "slug": "calate-helder",
  "coupleNames": "Calate & Helder",
  "displayNames": "Calate e Helder",
  "bride": "Calate Salazar Hojuane",
  "groom": "Hélder Jorge Muianga",
  "monogram": "CH",
  "eventType": "Casamento",
  "language": "Português",
  "visualStyle": "Elegante e romântico",
  "colors": "Full back para os convidados",
  "dateISO": "2026-08-29T15:00:00+02:00",
  "eventDateLong": "29 de agosto de 2026",
  "rsvpDeadline": "30 de junho de 2026",
  "timezone": "Africa/Maputo",
  "verse": "É por isso que o homem deixa o seu pai e a sua mãe para se unir com a sua mulher, e os dois se tornam uma só pessoa.",
  "verseReference": "Gênesis 2:24 — NTLH",
  "brideParents": "",
  "groomParents": "",
  "ceremonyTitle": "Cerimónia Religiosa",
  "ceremonyPlace": "Igreja Universal de Marracuene",
  "ceremonyTime": "10:00",
  "ceremonyMap": "https://maps.google.com/?q=-25.741796,32.648743",
  "receptionTitle": "Copo de Água",
  "receptionPlace": "Eventos & Acomodações Águia",
  "receptionTime": "15:00",
  "receptionMap": "https://maps.google.com/?q=-25.741796,32.648743",
  "additionalTitle": "",
  "additionalPlace": "",
  "additionalTime": "",
  "photoTitle": "",
  "photoPlace": "",
  "photoTime": "",
  "welcomeDrinkTitle": "",
  "welcomeDrinkPlace": "",
  "welcomeDrinkTime": "",
  "supportContacts": "+258 87 465 3598",
  "supportWhatsapp": "+258874653598",
  "clientName": "Hélder Jorge Muianga",
  "clientEmail": "socratesfrancisco75@gmail.com",
  "clientCity": "Marracuene, Maputo, Moçambique",
  "estimatedGuests": 123,
  "guestRows": 82,
  "giftSectionType": "Lista de presentes",
  "bankAccounts": [],
  "mobilePayments": [],
  "program": [
    {
      "title": "Cerimónia Religiosa",
      "place": "Igreja Universal de Marracuene",
      "time": "10:00"
    },
    {
      "title": "Copo de Água",
      "place": "Eventos & Acomodações Águia",
      "time": "15:00"
    }
  ],
  "story": {},
  "letter": "Querido(a) convidado(a),\n\nCom alegria e gratidão, convidamo-lo(a) a fazer parte do nosso casamento. A sua presença tornará este momento ainda mais especial para nós.\n\nContamos consigo para celebrar este dia com fé, amor e alegria.\n\nCom gratidão,\nCalate e Helder",
  "audioYoutube": "",
  "audioMp3": "",
  "guestListVersion": "Lista dos convidados.docx — 82 registos",
  "guestListUpdatedAt": "2026-06-11",
  "features": {
    "qrCode": false,
    "checkin": false,
    "timeCapsule": false,
    "rsvp": true,
    "guestMessages": true,
    "gifts": true,
    "guestInfo": true
  }
};

window.LIRANDZO_GUESTS = [
  {
    "id": "calate-helder-001",
    "number": 1,
    "name": "Adelaide Muianga",
    "nome": "Adelaide Muianga",
    "token": "g_2dce27a55af98332ad412089",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-002",
    "number": 2,
    "name": "Admiro e Esposa",
    "nome": "Admiro e Esposa",
    "token": "g_770fdfed05b90e6ee481201d",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-003",
    "number": 3,
    "name": "Agnaldo e Esposa",
    "nome": "Agnaldo e Esposa",
    "token": "g_38a7fe2d501a3422f5a7e43d",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-004",
    "number": 4,
    "name": "Agy e Esposa",
    "nome": "Agy e Esposa",
    "token": "g_580866abed4b0063722f8481",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-005",
    "number": 5,
    "name": "Albino Mateus e Esposa",
    "nome": "Albino Mateus e Esposa",
    "token": "g_11ee72addde97da7d9f06d17",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-006",
    "number": 6,
    "name": "Alda",
    "nome": "Alda",
    "token": "g_de428c0901c5242530cb4476",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-007",
    "number": 7,
    "name": "Amelia Miambo",
    "nome": "Amelia Miambo",
    "token": "g_f3dcfdebe482b12db36e2ea3",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-008",
    "number": 8,
    "name": "Antonio Hobjuane e Esposa",
    "nome": "Antonio Hobjuane e Esposa",
    "token": "g_4b207854fe5722cf43eb7149",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-009",
    "number": 9,
    "name": "Artur Muianga",
    "nome": "Artur Muianga",
    "token": "g_2e037e6e3295548004ab4b18",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-010",
    "number": 10,
    "name": "Assau",
    "nome": "Assau",
    "token": "g_05efa25594640111fa8b9d6b",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-011",
    "number": 11,
    "name": "Belmiro Lumbela",
    "nome": "Belmiro Lumbela",
    "token": "g_b1d859052e0e2318124f051e",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-012",
    "number": 12,
    "name": "Bento Munguambe e Esposa",
    "nome": "Bento Munguambe e Esposa",
    "token": "g_34a6fb0050252ec8bdbb3a4e",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-013",
    "number": 13,
    "name": "Bernardo e Esposa",
    "nome": "Bernardo e Esposa",
    "token": "g_41f19df0e8e8304335120181",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-014",
    "number": 14,
    "name": "Berta Muianga",
    "nome": "Berta Muianga",
    "token": "g_2b2d8c9580499724b1f1f8aa",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-015",
    "number": 15,
    "name": "Carla Banze",
    "nome": "Carla Banze",
    "token": "g_59210517158d828e8288df6d",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-016",
    "number": 16,
    "name": "Carlitos e Esposa",
    "nome": "Carlitos e Esposa",
    "token": "g_409c65cd25e6fb2a9494d5b1",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-017",
    "number": 17,
    "name": "Carlos e Esposa",
    "nome": "Carlos e Esposa",
    "token": "g_8e919c4308bf85a5457f641c",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-018",
    "number": 18,
    "name": "Carlos Macuacua e Esposa",
    "nome": "Carlos Macuacua e Esposa",
    "token": "g_412524c64bc320b1fda02b4b",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-019",
    "number": 19,
    "name": "César Langa",
    "nome": "César Langa",
    "token": "g_ae4ede457e530c11b1acdb3d",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-020",
    "number": 20,
    "name": "Claudio Muianga",
    "nome": "Claudio Muianga",
    "token": "g_84629522b9b5b5f9fe37e979",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-021",
    "number": 21,
    "name": "Cremildo e Esposa",
    "nome": "Cremildo e Esposa",
    "token": "g_77a6270b2a3c282a92f94afe",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-022",
    "number": 22,
    "name": "Crisalda Langa e Esposo",
    "nome": "Crisalda Langa e Esposo",
    "token": "g_bf75601e20f6c772b6cdc56c",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-023",
    "number": 23,
    "name": "Daniel Castigo e Esposa",
    "nome": "Daniel Castigo e Esposa",
    "token": "g_d2ff76bc87d7e3c08ccb2628",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-024",
    "number": 24,
    "name": "Dinis Manhice",
    "nome": "Dinis Manhice",
    "token": "g_2aee48d3306c52e1ea7cb69c",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-025",
    "number": 25,
    "name": "Efigenio Mandlate",
    "nome": "Efigenio Mandlate",
    "token": "g_63cd9ebc27055be417f511c4",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-026",
    "number": 26,
    "name": "Emidio Tovela",
    "nome": "Emidio Tovela",
    "token": "g_2b677e273d65e9704dc2218b",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-027",
    "number": 27,
    "name": "Eunice Manhiça",
    "nome": "Eunice Manhiça",
    "token": "g_e4d487f4164fa85255c568c2",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-028",
    "number": 28,
    "name": "Filomena Trita",
    "nome": "Filomena Trita",
    "token": "g_1861318840f58c1abcbc4c0a",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-029",
    "number": 29,
    "name": "Francisca Titi",
    "nome": "Francisca Titi",
    "token": "g_447d14e66db5dedc621285c1",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-030",
    "number": 30,
    "name": "Francisco Lumbela",
    "nome": "Francisco Lumbela",
    "token": "g_68843e53a83a6ba6e14e8343",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-031",
    "number": 31,
    "name": "Francisco Mateus e Esposa",
    "nome": "Francisco Mateus e Esposa",
    "token": "g_0c21e73660b6a00c4eb2ccce",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-032",
    "number": 32,
    "name": "Gildo e Esposa",
    "nome": "Gildo e Esposa",
    "token": "g_2c89aae69aef1859df5ee307",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-033",
    "number": 33,
    "name": "Gildo Tamele e Esposa",
    "nome": "Gildo Tamele e Esposa",
    "token": "g_9fd8d1021421dcf55b5293d9",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-034",
    "number": 34,
    "name": "Gino Bsilio e Esposa",
    "nome": "Gino Bsilio e Esposa",
    "token": "g_57c9bb9c48fce52ef9b678a9",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-035",
    "number": 35,
    "name": "Helton Sergio",
    "nome": "Helton Sergio",
    "token": "g_f3bdd660ef7e6aab2d2d63a2",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-036",
    "number": 36,
    "name": "Hilario Muianga",
    "nome": "Hilario Muianga",
    "token": "g_84c324be14a2a3bcf481cf66",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-037",
    "number": 37,
    "name": "Hilario Palma e Esposa",
    "nome": "Hilario Palma e Esposa",
    "token": "g_83b0bb9fdf8e349530c6f2b0",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-038",
    "number": 38,
    "name": "Ilda e Esposo",
    "nome": "Ilda e Esposo",
    "token": "g_2c57ebc5ea9164af60a3e6a1",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-039",
    "number": 39,
    "name": "Ines Munguambe e Esposo",
    "nome": "Ines Munguambe e Esposo",
    "token": "g_100771c2c89f736dfb3ecd1d",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-040",
    "number": 40,
    "name": "Isau e Esposa",
    "nome": "Isau e Esposa",
    "token": "g_ab18b3db654b73ce4e2eeade",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-041",
    "number": 41,
    "name": "Jaquelina",
    "nome": "Jaquelina",
    "token": "g_cd04b794c0505386dd53411b",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-042",
    "number": 42,
    "name": "Jerry",
    "nome": "Jerry",
    "token": "g_528a357abe5e83956d86840a",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-043",
    "number": 43,
    "name": "Jorge Mateus e Esposa",
    "nome": "Jorge Mateus e Esposa",
    "token": "g_312273b34d90707d7487e0c7",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-044",
    "number": 44,
    "name": "Jorge Muianga",
    "nome": "Jorge Muianga",
    "token": "g_33598367bb5cf6d8fb3a84cd",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-045",
    "number": 45,
    "name": "Jove",
    "nome": "Jove",
    "token": "g_f3bb4503ba7460f21e129cf0",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-046",
    "number": 46,
    "name": "Julio Agibo e Esposa",
    "nome": "Julio Agibo e Esposa",
    "token": "g_b96d06423c69078686efd42c",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-047",
    "number": 47,
    "name": "Leonel Machanguana",
    "nome": "Leonel Machanguana",
    "token": "g_6744085cc7ec920de30a36c6",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-048",
    "number": 48,
    "name": "Lourenço Nhamue",
    "nome": "Lourenço Nhamue",
    "token": "g_c967a3df1e3f126010788626",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-049",
    "number": 49,
    "name": "Magrete",
    "nome": "Magrete",
    "token": "g_83cb66fb182c7016baf08995",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-050",
    "number": 50,
    "name": "Mama Isabel",
    "nome": "Mama Isabel",
    "token": "g_9cddd4f0257dbb4ebabef801",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-051",
    "number": 51,
    "name": "Manusao e Esposa",
    "nome": "Manusao e Esposa",
    "token": "g_c5d206e8dfbce0581c0b8a7a",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-052",
    "number": 52,
    "name": "Marcela de Morais",
    "nome": "Marcela de Morais",
    "token": "g_87e40b90a847c0dc9bd43ef7",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-053",
    "number": 53,
    "name": "Marcelo e Esposa",
    "nome": "Marcelo e Esposa",
    "token": "g_1bcc66b1b163e4272de5d9a2",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-054",
    "number": 54,
    "name": "Marcia e Esposo",
    "nome": "Marcia e Esposo",
    "token": "g_e0d499a85dab028313537f8e",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-055",
    "number": 55,
    "name": "Margarida Muianga",
    "nome": "Margarida Muianga",
    "token": "g_6ec62765bb68efa212fe1bdd",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-056",
    "number": 56,
    "name": "Mequelina e Esposo",
    "nome": "Mequelina e Esposo",
    "token": "g_ba43d6b64c7bd3f2a2d6f6ae",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-057",
    "number": 57,
    "name": "Miguel e Esposa",
    "nome": "Miguel e Esposa",
    "token": "g_20ebfc7846c555a5dd15a9e5",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-058",
    "number": 58,
    "name": "Miranda e Esposo",
    "nome": "Miranda e Esposo",
    "token": "g_3f635dacaeea225de7010147",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-059",
    "number": 59,
    "name": "Neninha e Esposo",
    "nome": "Neninha e Esposo",
    "token": "g_de8ae6b5a5b850a56b2e7215",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-060",
    "number": 60,
    "name": "Nercia Muianga",
    "nome": "Nercia Muianga",
    "token": "g_a3c5e56385ad1af457b3bb3b",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-061",
    "number": 61,
    "name": "Olinda e Esposo",
    "nome": "Olinda e Esposo",
    "token": "g_8b32bd67fb35a1a5b0f83a7a",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-062",
    "number": 62,
    "name": "Pai Muianga",
    "nome": "Pai Muianga",
    "token": "g_bfbd33289b014820f5606054",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-063",
    "number": 63,
    "name": "Pedro e Esposa",
    "nome": "Pedro e Esposa",
    "token": "g_53d412d0ce91fd1c706b15ea",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-064",
    "number": 64,
    "name": "Pinto e Esposa",
    "nome": "Pinto e Esposa",
    "token": "g_d2996052f980b9cf7b5a708d",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-065",
    "number": 65,
    "name": "Pinto filho 1",
    "nome": "Pinto filho 1",
    "token": "g_76eec2ff2f7a53f60b960780",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-066",
    "number": 66,
    "name": "Pinto Filho 2",
    "nome": "Pinto Filho 2",
    "token": "g_3a503711f1c3c8ef52b1fe6f",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-067",
    "number": 67,
    "name": "Pinto Filho 3",
    "nome": "Pinto Filho 3",
    "token": "g_ea84c0933fa544453125312f",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-068",
    "number": 68,
    "name": "Pinto Filho 4",
    "nome": "Pinto Filho 4",
    "token": "g_7a6409586a130761d4729368",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-069",
    "number": 69,
    "name": "Ramos",
    "nome": "Ramos",
    "token": "g_c9c46cef77070671c456cba9",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-070",
    "number": 70,
    "name": "Raul Guezimane e Esposa",
    "nome": "Raul Guezimane e Esposa",
    "token": "g_3dcd046efbb8ebcb07dfbb29",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-071",
    "number": 71,
    "name": "Roberto e Esposa",
    "nome": "Roberto e Esposa",
    "token": "g_2bcf06e47d6973c64ecb53d1",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-072",
    "number": 72,
    "name": "Rolina",
    "nome": "Rolina",
    "token": "g_47d8b89a1b865b2dd7877103",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-073",
    "number": 73,
    "name": "Rosa Muianga",
    "nome": "Rosa Muianga",
    "token": "g_d26f6d60b0b333ab7178fe57",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-074",
    "number": 74,
    "name": "Sarito e Esposa",
    "nome": "Sarito e Esposa",
    "token": "g_a64567e59f1f7bad38d9b22d",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-075",
    "number": 75,
    "name": "Sergio e Esposa",
    "nome": "Sergio e Esposa",
    "token": "g_b67f29928ce340ddf02ce465",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-076",
    "number": 76,
    "name": "Sergio Muianga e Esposa",
    "nome": "Sergio Muianga e Esposa",
    "token": "g_2f6fba60d2a4c02f50f42429",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-077",
    "number": 77,
    "name": "Silvia Muianga",
    "nome": "Silvia Muianga",
    "token": "g_fed473e7a01b3df2eeefc29e",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-078",
    "number": 78,
    "name": "Socrates Mateus e Esposa",
    "nome": "Socrates Mateus e Esposa",
    "token": "g_31aefe6d46dd3101ef3e6a74",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-079",
    "number": 79,
    "name": "Taxinha",
    "nome": "Taxinha",
    "token": "g_e789d4f8d68869edd29a74a1",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-080",
    "number": 80,
    "name": "Tino e Esposa",
    "nome": "Tino e Esposa",
    "token": "g_b33f9df43a2313ce372ac61d",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-081",
    "number": 81,
    "name": "Vovo Zunguza e Esposa",
    "nome": "Vovo Zunguza e Esposa",
    "token": "g_0798df640ccd9c8e17a415f9",
    "mesa": "A definir",
    "table": "A definir",
    "category": "couple",
    "maxGuests": 2,
    "maxGuestsTotal": 2,
    "companions": 1,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  },
  {
    "id": "calate-helder-082",
    "number": 82,
    "name": "Zito Mateus",
    "nome": "Zito Mateus",
    "token": "g_c24b6613db3a378757a8b4be",
    "mesa": "A definir",
    "table": "A definir",
    "category": "individual",
    "maxGuests": 1,
    "maxGuestsTotal": 1,
    "companions": 0,
    "status": "Não aberto",
    "guestStatus": "Não aberto",
    "checkedIn": false,
    "phone": "",
    "notes": ""
  }
];
